# Generated by Django 4.1 on 2025-06-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_enfermeira', models.CharField(max_length=255)),
                ('email_enfermeira', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_paciente', models.CharField(max_length=255)),
                ('idade_do_paciente', models.IntegerField()),
                ('medicamento_paciente', models.CharField(max_length=255)),
                ('via_paciente', models.CharField(max_length=255)),
                ('dose_unidade_paciente', models.CharField(max_length=255)),
                ('frequencia_paciente', models.IntegerField()),
                ('data_paciente', models.DateField()),
                ('horario_paciente', models.TimeField()),
                ('observacoes_paciente', models.TextField(blank=True, default='')),
            ],
        ),
    ]
